### PR TITLE
image.bat: truncated the unnecessary parts of the script

### PR DESCRIPTION
**Pull request by o0Eidolon0o**
Removed the unnecessary UAC elevation pop-up since the built in one is there anyway. Removed all the elses and unnecessary gotos, simplified the if statements. Randomised result name and hit it in %temp%.

### CODE REVIEW

**Comment by shinthebean1** [comment]
Few things I don't like about the new changes:

I think we should keep the prompt at the start because we should tell the users before starting the script as an Administrator because it's kinda weird to download a batch file and it just instantly asks for Admin;

We shouldn't download the results for checkhealth in %temp% because of AV's

I uploaded new code to fix an issue where it would throw a "file path cant be found" error, and added sfc to the no network lines instead of throwing a prompt. <--- new code should be re-reviewed

**Comment by o0Eidolon0o** [comment]
Like I mentioned, the pwsh pop-up is arbitrary in my opinion. What other choice does the user really have? Suppose there is an argument to be made that the user is at least notified, but overall it's something that just adds time unnecessarily.

> We shouldn't download the results for checkhealth in %temp% because of AV's

Care to elaborate? I am unaware of this being a root of any issues or overall being a cause of concern as the files don't really include anything particularly interesting anyway, and this just neatly shoves them away.

**Comment by shinthebean1** [comment]
> Like I mentioned, the pwsh pop-up is arbitrary in my opinion. What other choice does the user really have? Suppose there is an argument to be made that the user is at least notified, but overall it's something that just adds time unnecessarily.
> 
> > We shouldn't download the results for checkhealth in %temp% because of AV's
> > Care to elaborate? I am unaware of this being a root of any issues or overall being a cause of concern as the files don't really include anything particularly interesting anyway, and this just neatly shoves them away.

That's fair; But what about the %temp%? AV's flag it as a virus because something's being rapidly created and deleted from %temp% where viruses hide (from my experience and from what I've seen)

Also bug with code:
When no corruption found and it goes to :sfc, when sfc is done it says 3/3 finished for only one command which makes no sense so i think we should just do sfc both after restorehealth and after having no corruption detected

Another bug with code:

image
^^ Ignore the pause, was testing what it does when corruption detected; but this happens when corruption is detected

**Comment by shinthebean1** [comment]
> Care to elaborate? I am unaware of this being a root of any issues or overall being a cause of concern as the files don't really include anything particularly interesting anyway, and this just neatly shoves them away.

I don't really know what to elaborate on; It was getting blocked by windows defender (not letting them install with real time protection on), Avast AV was blocking it, and a few other AV's and it has ok behavior results on virustotal: https://www.virustotal.com/gui/file/40300d6fac282dbbf7677e1f3d429b2c4d3a94b0b830eb75df3eaa7c1a1856e7/behavior

**Comment by o0Eidolon0o** [comment]
> When no corruption found and it goes to :sfc, when sfc is done it says 3/3 
finished for only one command which makes no sense so i think we should just do sfc both after restorehealth and after having no corruption detected
I see two possible resolutions that would not necessitate bloating the script again:
1.  Have the commands show their actual output. This would be beneficial since all of those commands have built in progress bars
2. Have it say the name of the command (sfc, scanhealth...) instead
Personally a fan of option 1, no reason to replace a perfectly good output just to add a silly little echo right under it. 
> I don't really know what to elaborate on; It was getting blocked by windows defender (not letting them install with real time protection on), Avast AV was blocking it, and a few other AV's and it has ok behavior results on virustotal:

I have not seen this behaviour on my machine, nor on any other machines. I am fairly certain I used %temp% file creation multiple times, including my finals work, and never saw an issue with this.
> ^^ Ignore the pause, was testing what it does when corruption detected; but this happens when corruption is detected

This is not my code, my code's messaging is different. I'd check your if conditions, I think I had to change them to work.

**Comment by shinthebean1** [comment]
Is there a way to edit the code and publish it in this post as a new push?
I’ll edit it when I get back home I’ll try not to bloat it

**Comment by o0Eidolon0o** [comment]
I can see your commit from an hour ago if that's what you are talking about. Otherwise, sort out file conflicts and merge (or refuse the request)

**Comment by shinthebean1** [comment]
For this do you mean like:

Echo DISM /Online /Cleanup-Image /RestoreHealth
DISM blah blah
Echo sfc/scannow
Sfc/scannow

Or

echo dism /online /cleanup-image /restorehealth
Dism /online /cleanup-image /restorehealth >nul 2>&1
Echo sfc /scannow
Sfc/scannow >nul 2>&1

So either say and show the output of the commands or say output of commands
and suppress the output

**Comment by o0Eidolon0o** [comment]
I added another commit with what I think should be the way to do it. The other option that I see as okay is to keep your way of just using echo for progress reports, but rather than saying x/3 finished, say 'sfc has finished', 'scanhealth' has finished etc.

**Comment by shinthebean1** [comment]
> I added another commit with what I think should be the way to do it. The other option that I see as okay is to keep your way of just using echo for progress reports, but rather than saying x/3 finished, say 'sfc has finished', 'scanhealth' has finished etc.

Ok, I'll add my own edits to it and post it on here and lmk what you think

**Pull request merged**
